### ISSUE TITLE
Unable to compile dependencies with recent versions.

### ISSUE THREAD

**Issue by hickscorp** [Diamond/pxblog#21]
Using elixir 1.4.2 along with erlang 19.3, the dependencies cannot be compiled:

```
Compiling src/ec_file.erl failed:
ERROR: compile failed while processing /home/doodloo/pxblog/deps/erlware_commons: rebar_abort
==> pxblog
** (Mix) Could not compile dependency :erlware_commons, "/home/doodloo/.mix/rebar compile skip_deps=true deps_dir="/home/doodloo/pxblog/_build/dev/lib"" command failed. You can recompile this dependency with "mix deps.compile erlware_commons", update it with "mix deps.update erlware_commons" or clean it with "mix deps.clean erlware_commons"
```

**Comment by CharlesIrvineKC** [comment]
Same problem here. This is a great tutorial. Thanks

**Comment by richeyb** [comment]
Try this out now; I had a separate project to update this to the latest and greatest which is now merged into master. Everything is compiling and working locally now!

**Comment by CharlesIrvineKC** [comment]
Yup, I’m up and running. Very cool project. 

Last week I resigned from my job with the “man” to start working on my own product idea. Without giving too much away, I describe it as “wikipedia on steroids”.

Pgblog will be my seed project. A year from now I’ll send you a link for a free subscription. 

Thanks and best regards,
Chuck Irvine

**Comment by richeyb** [comment]
Closing the issue since it seems to have taken care of things!
